"""Interactive ``photochron init`` wizard.

Goal: collapse the first-run friction (edit config.yaml, edit anchors.yaml,
verify model licenses, remember to opt in to face + LLM) into a single
prompt-driven session. Runs without external services; doesn't download
anything; safe to re-run.

Designed to be easy to script:
- ``--no-input`` skips every prompt and writes safe defaults.
- ``--force`` overwrites existing files instead of asking for confirmation.
- All inputs accept defaults shown in ``[brackets]`` — pressing Enter is
  always a valid answer.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml
from rich.console import Console
from rich.prompt import Confirm, Prompt

console = Console()


# Known-safe, commonly-used model strings. We surface these in the wizard
# but the user can override or skip — there is still no hardcoded default
# anywhere on the runtime path. License verification stays the user's job;
# the wizard nudges with the license URL.
_FACE_MODEL_CHOICES = ("buffalo_l", "buffalo_s")
_PRIMARY_LLM_CHOICES = ("llava-next:7b", "llava:7b")
_FALLBACK_LLM_CHOICES = ("moondream2", "llava:7b")


@dataclass
class InitAnswers:
    """Container so tests can drive the wizard with pre-canned answers."""

    photos_dir: str
    output_dir: str
    face_model: str  # may be ""
    primary_llm: str  # may be ""
    fallback_llm: str  # may be ""
    extract_gps: bool
    write_anchors_template: bool


def collect_answers(
    no_input: bool,
    photos_dir_default: str = "./photos",
    output_dir_default: str = "./photochron_output",
) -> InitAnswers:
    """Drive the prompt loop. Each question shows its default in brackets."""

    if no_input:
        return InitAnswers(
            photos_dir=photos_dir_default,
            output_dir=output_dir_default,
            face_model="",
            primary_llm="",
            fallback_llm="",
            extract_gps=False,
            write_anchors_template=False,
        )

    console.print("[bold]photochron — first-time setup[/bold]")
    console.print(
        "[dim]Press Enter to accept the default shown in [brackets]. "
        "Empty model values mean 'do not configure that layer yet — I'll "
        "uncomment it later after reviewing licenses'.[/dim]\n"
    )

    photos = Prompt.ask("Photos directory", default=photos_dir_default)
    output = Prompt.ask("Output directory", default=output_dir_default)

    console.print()
    console.print(
        "[bold]Face layer (InsightFace)[/bold]\n"
        "[dim]Verify license at https://github.com/deepinsight/insightface "
        "before enabling.[/dim]"
    )
    face = Prompt.ask(
        "Face model name (leave blank to skip)",
        default="",
        show_default=False,
        choices=[*_FACE_MODEL_CHOICES, ""],
    )

    console.print()
    console.print(
        "[bold]Context layer (Ollama vision LLM)[/bold]\n"
        "[dim]Verify licenses at https://ollama.com/library before enabling.[/dim]"
    )
    primary = Prompt.ask(
        "Primary vision model (leave blank to skip)",
        default="",
        show_default=False,
        choices=[*_PRIMARY_LLM_CHOICES, ""],
    )
    fallback = ""
    if primary:
        fallback = Prompt.ask(
            "Fallback vision model (leave blank for none)",
            default="",
            show_default=False,
            choices=[*_FALLBACK_LLM_CHOICES, ""],
        )

    console.print()
    extract_gps = Confirm.ask(
        "Extract GPS coordinates from EXIF? (default no — GPS can de-anonymize shared reports)",
        default=False,
    )

    console.print()
    write_anchors = Confirm.ask(
        "Write an anchors.yaml template alongside config.yaml? (birthdays + events guide chronological sorting)",
        default=False,
    )

    return InitAnswers(
        photos_dir=photos,
        output_dir=output,
        face_model=face,
        primary_llm=primary,
        fallback_llm=fallback,
        extract_gps=extract_gps,
        write_anchors_template=write_anchors,
    )


def render_config_yaml(answers: InitAnswers) -> str:
    """Serialize the wizard answers into a config.yaml compatible with Config."""
    cfg: dict[str, object] = {
        "version": "1.0",
        "paths": {
            "cache_dir": ".photochron",
            "thumbs_dir": ".photochron/thumbs",
            "output_dir": answers.output_dir,
        },
        "ingestion": {
            "extract_gps": answers.extract_gps,
        },
        "face": {
            "model_name": answers.face_model,
        },
        "context": {
            "primary_model": answers.primary_llm,
            "fallback_model": answers.fallback_llm,
        },
    }

    header = (
        "# photochron config — generated by `photochron init`.\n"
        "# Review every value, then re-run `photochron doctor` to verify\n"
        "# that the models you selected are actually installed.\n\n"
    )
    return header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False)


def render_anchors_template() -> str:
    """Return the template anchors.yaml shipped with the repo verbatim."""
    return (Path(__file__).parent.parent.parent.parent / "anchors.yaml").read_text(encoding="utf-8")


def _ask_overwrite(path: Path, *, no_input: bool, force: bool) -> bool:
    if not path.exists():
        return True
    if force:
        return True
    if no_input:
        # Conservative default in non-interactive mode: never overwrite.
        return False
    return Confirm.ask(f"{path} exists. Overwrite?", default=False)


def write_files(
    answers: InitAnswers,
    target_dir: Path,
    *,
    no_input: bool = False,
    force: bool = False,
) -> tuple[Path, Path | None]:
    """Write config.yaml (and optionally anchors.yaml). Returns the paths
    that were actually written (anchors path is ``None`` if skipped)."""

    target_dir.mkdir(parents=True, exist_ok=True)

    config_path = target_dir / "config.yaml"
    if _ask_overwrite(config_path, no_input=no_input, force=force):
        config_path.write_text(render_config_yaml(answers), encoding="utf-8")
        console.print(f"[green]✓[/green] wrote {config_path}")
    else:
        console.print(f"[yellow]·[/yellow] kept existing {config_path}")

    anchors_path: Path | None = None
    if answers.write_anchors_template:
        anchors_path = target_dir / "anchors.yaml"
        if _ask_overwrite(anchors_path, no_input=no_input, force=force):
            try:
                anchors_path.write_text(render_anchors_template(), encoding="utf-8")
                console.print(f"[green]✓[/green] wrote {anchors_path}")
            except FileNotFoundError:
                # Repo template not available (e.g. running from a wheel).
                # Fall back to a minimal one.
                anchors_path.write_text(
                    "# photochron anchors — fill in your own persons/events.\n"
                    "persons: []\nevents: []\nknown_dates: []\n",
                    encoding="utf-8",
                )
                console.print(f"[green]✓[/green] wrote minimal {anchors_path}")
        else:
            console.print(f"[yellow]·[/yellow] kept existing {anchors_path}")
            anchors_path = None

    return config_path, anchors_path


def print_next_steps(config_path: Path, anchors_path: Path | None) -> None:
    """Tell the user what to do next — the single most important UX moment."""
    console.print()
    console.print("[bold]Next steps[/bold]")
    console.print(f"  1. Review [cyan]{config_path}[/cyan].")
    if anchors_path:
        console.print(f"  2. Add your persons / events to [cyan]{anchors_path}[/cyan].")
    console.print("  3. Run [cyan]photochron doctor[/cyan] to verify Ollama is reachable and models are installed.")
    console.print("  4. Run [cyan]photochron run --input <photo_dir>[/cyan] to start the pipeline.")
